application: keykeytools
version: 2
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /script
  static_dir: script
- url: /onekey.*
  script: classes/onekey.py
- url: /mskkconverter
  script: classes/mskkconverter.py
- url: /msgoingconverter
  script: classes/msgoingconverter.py
- url: .*
  script: classes/main.py
